(()=>{
const {supabaseClient,CFG}=window.ReceiptsApp;const root=document.getElementById('root');let S={profile:null,settings:null,requests:[],receipts:[],view:'dashboard'};
function roleName(r){return r==='admin'?'Administrador':'Contabilidade'}
function withTimeout(promise,ms=4000){return Promise.race([promise,new Promise((_,reject)=>setTimeout(()=>reject(new Error('timeout')),ms))])}
async function boot(){
  login();
  if(!supabaseClient){
    const x=document.getElementById('loginErr');
    if(x){x.textContent='Não foi possível conectar ao serviço de dados. Atualize a página e tente novamente.';x.classList.remove('hidden')}
    return;
  }
  try{
    const result=await withTimeout(supabaseClient.auth.getSession(),3500);
    const session=result?.data?.session;
    if(!session)return;
    const {data:p,error}=await withTimeout(supabaseClient.from('profiles').select('*').eq('id',session.user.id).single(),5000);
    if(error||!p||!['admin','accounting'].includes(p.role)){await supabaseClient.auth.signOut();const x=document.getElementById('loginErr');if(x){x.textContent='Este usuário não possui acesso autorizado ao sistema.';x.classList.remove('hidden')}return}
    S.profile={...p,email:session.user.email};
    await load();
    shell();
  }catch(err){
    console.warn('Inicialização do painel:',err);
  }
}
function login(){
  root.innerHTML='<div class="login-wrap"><div class="login-card"><div class="brand"><img class="brand-logo brand-logo-large" src="https://i.postimg.cc/09t8GNX6/LOGO-TRILHEIROS-Photoroom.png" alt="Logo Trilheiros de Rondonópolis"><div><h1 style="font-size:17px;margin:0">Trilheiros de Rondonópolis</h1><small style="color:#657168">Gestão de Recibos</small></div></div><h1>Acesso ao sistema</h1><p>Acesso restrito ao Administrador e à Contabilidade.</p><form id="login"><div class="field"><label>E-mail</label><input name="email" type="email" required autocomplete="email" placeholder="Digite seu e-mail"></div><div style="height:12px"></div><div class="field"><label>Senha</label><div class="password-field"><input id="loginPassword" name="password" type="password" required autocomplete="current-password" placeholder="Digite sua senha"><button class="password-eye" type="button" id="toggleLoginPassword" aria-label="Mostrar senha" title="Mostrar senha">👁</button></div></div><div id="loginErr" class="notice error hidden"></div><div class="actions"><button class="btn btn-primary" style="width:100%">Entrar no painel</button></div></form><div class="notice info" style="margin-top:16px">Somente dois perfis são autorizados: <strong>Administrador</strong> e <strong>Contabilidade</strong>.</div></div></div>';

  const eye=document.getElementById('toggleLoginPassword');
  eye.onclick=()=>{
    const input=document.getElementById('loginPassword');
    const show=input.type==='password';
    input.type=show?'text':'password';
    eye.textContent=show?'🙈':'👁';
    eye.setAttribute('aria-label',show?'Ocultar senha':'Mostrar senha');
    eye.title=show?'Ocultar senha':'Mostrar senha';
  };

  document.getElementById('login').onsubmit=async e=>{
    e.preventDefault();
    const form=e.currentTarget,btn=form.querySelector('button.btn-primary'),x=document.getElementById('loginErr');
    x.classList.add('hidden');
    if(!supabaseClient){x.textContent='Serviço de dados indisponível. Atualize a página.';x.classList.remove('hidden');return}
    btn.disabled=true;btn.textContent='Entrando...';
    try{
      const {error}=await withTimeout(supabaseClient.auth.signInWithPassword({email:form.email.value.trim(),password:form.password.value}),8000);
      if(error)throw error;
      await boot();
    }catch(err){
      x.textContent=err?.message==='timeout'?'A conexão demorou demais. Tente novamente.':'Não foi possível entrar. Confira e-mail e senha.';
      x.classList.remove('hidden');
    }finally{btn.disabled=false;btn.textContent='Entrar no painel'}
  };
}
async function load(){const [a,b,c]=await Promise.all([supabaseClient.from('app_settings').select('*').eq('id',1).single(),supabaseClient.from('receipt_requests').select('*').order('created_at',{ascending:false}),supabaseClient.from('receipts').select('*').order('created_at',{ascending:false})]);S.settings=a.data||{};S.requests=b.data||[];S.receipts=c.data||[]}
function shell(){const admin=S.profile.role==='admin';root.innerHTML=`<div class="admin-shell"><aside class="sidebar"><div class="brand"><img class="brand-logo" src="https://i.postimg.cc/09t8GNX6/LOGO-TRILHEIROS-Photoroom.png" alt="Logo Trilheiros de Rondonópolis"><div><h1>Trilheiros</h1><small>Gestão de Recibos</small></div></div><nav class="nav"><button data-v="dashboard">Visão geral</button><button data-v="receipts">Recibos</button><button data-v="requests">Solicitações</button>${admin?'<button data-v="new">+ Novo recibo</button><button data-v="settings">Configurações</button>':''}</nav><div class="sidebar-foot"><div class="user"><strong>${escapeHtml(S.profile.display_name)}</strong><br><span style="color:#bfd3c5">${roleName(S.profile.role)}</span></div><button id="logout" class="btn btn-secondary btn-sm" style="width:100%;margin-top:9px">Sair</button></div></aside><main class="admin-main"><div id="content"></div></main></div>`;root.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{S.view=b.dataset.v;render()});document.getElementById('logout').onclick=async()=>{await supabaseClient.auth.signOut();location.reload()};render()}
function reqFor(r){return S.requests.find(q=>q.id===r.request_id)||{}}
function render(){root.querySelectorAll('[data-v]').forEach(b=>b.classList.toggle('active',b.dataset.v===S.view));({dashboard,receipts,requests,newReq,settings}[S.view]||dashboard)()}
function dashboard(){const now=new Date(),month=S.receipts.filter(r=>{const d=new Date(r.created_at);return d.getMonth()===now.getMonth()&&d.getFullYear()===now.getFullYear()}),total=month.reduce((a,b)=>a+Number(b.amount_received||0),0),pending=S.requests.filter(x=>requestStatus(x)==='pending').length;document.getElementById('content').innerHTML=`<div class="admin-head"><div><h2>Visão geral</h2><p>Controle de recibos e pagamentos a fornecedores.</p></div>${S.profile.role==='admin'?'<button class="btn btn-primary" id="newBtn">+ Solicitar recibo</button>':''}</div><div class="kpis"><div class="kpi"><span>Recibos no mês</span><strong>${month.length}</strong></div><div class="kpi"><span>Valor documentado</span><strong>${brl(total)}</strong></div><div class="kpi"><span>Aguardando fornecedor</span><strong>${pending}</strong></div><div class="kpi"><span>Total arquivado</span><strong>${S.receipts.length}</strong></div></div><div class="panel"><h3>Últimos recibos</h3>${tableReceipts(S.receipts.slice(0,8))}</div>`;document.getElementById('newBtn')?.addEventListener('click',()=>{S.view='new';render()});wireReceipt()}
function tableReceipts(rows){if(!rows.length)return'<div class="empty">Nenhum recibo encontrado.</div>';return'<div class="table-wrap"><table><thead><tr><th>Recibo</th><th>Fornecedor</th><th>Referência</th><th>Categoria</th><th>Data</th><th>Valor</th><th>Ações</th></tr></thead><tbody>'+rows.map(r=>{const q=reqFor(r);return`<tr><td><strong>${escapeHtml(r.receipt_code||'—')}</strong></td><td>${escapeHtml(r.legal_name)}<br><span class="muted">${formatCpfCnpj(r.cpf_cnpj)}</span></td><td>${escapeHtml(q.event_name||'—')}</td><td>${escapeHtml(q.category||'—')}</td><td>${dateBR(r.payment_date)}</td><td class="money">${brl(r.amount_received)}</td><td><div class="table-actions"><button class="btn btn-secondary btn-sm" data-open="${r.id}">Ver</button><button class="btn btn-primary btn-sm" data-pdf="${r.id}">PDF</button></div></td></tr>`}).join('')+'</tbody></table></div>'}
function wireReceipt(){document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openReceipt(b.dataset.open));document.querySelectorAll('[data-pdf]').forEach(b=>b.onclick=()=>{const r=S.receipts.find(x=>x.id===b.dataset.pdf);if(r)generateReceiptPDF(r,reqFor(r),S.settings)})}
function receipts(){const years=[...new Set(S.receipts.map(r=>new Date(r.created_at).getFullYear()))].sort((a,b)=>b-a);document.getElementById('content').innerHTML=`<div class="admin-head"><div><h2>Recibos arquivados</h2><p>Filtre por mês e ano e gere o PDF quando precisar.</p></div><button class="btn btn-secondary" id="csv">Exportar CSV</button></div><div class="toolbar"><div class="field"><label>Mês</label><select id="fm"><option value="">Todos</option>${Array.from({length:12},(_,i)=>'<option value="'+(i+1)+'">'+new Date(2020,i).toLocaleDateString('pt-BR',{month:'long'})+'</option>').join('')}</select></div><div class="field"><label>Ano</label><select id="fy"><option value="">Todos</option>${years.map(y=>'<option>'+y+'</option>').join('')}</select></div><div class="field search"><label>Buscar</label><input id="fq" placeholder="Fornecedor, CPF/CNPJ, passeio..."></div></div><div id="list"></div>`;['fm','fy'].forEach(id=>document.getElementById(id).onchange=filterReceipts);document.getElementById('fq').oninput=filterReceipts;document.getElementById('csv').onclick=exportCSV;filterReceipts()}
function filtered(){const m=Number(document.getElementById('fm')?.value||0),y=Number(document.getElementById('fy')?.value||0),q=(document.getElementById('fq')?.value||'').toLowerCase();return S.receipts.filter(r=>{const d=new Date(r.created_at),rq=reqFor(r),hay=(r.legal_name+' '+r.cpf_cnpj+' '+(rq.event_name||'')+' '+(rq.category||'')).toLowerCase();return(!m||d.getMonth()+1===m)&&(!y||d.getFullYear()===y)&&(!q||hay.includes(q))})}
function filterReceipts(){const rows=filtered(),sum=rows.reduce((a,b)=>a+Number(b.amount_received||0),0);document.getElementById('list').innerHTML='<div class="panel"><strong>'+rows.length+' recibo(s) • '+brl(sum)+'</strong><div style="height:12px"></div>'+tableReceipts(rows)+'</div>';wireReceipt()}
function requests(){document.getElementById('content').innerHTML=`<div class="admin-head"><div><h2>Solicitações</h2><p>Links enviados aos fornecedores.</p></div>${S.profile.role==='admin'?'<button class="btn btn-primary" id="newBtn">+ Nova solicitação</button>':''}</div><div class="table-wrap"><table><thead><tr><th>Referência</th><th>Categoria</th><th>Valor previsto</th><th>Expira</th><th>Status</th><th>Ações</th></tr></thead><tbody>${S.requests.map(r=>{const s=requestStatus(r);return`<tr><td>${escapeHtml(r.event_name)}</td><td>${escapeHtml(r.category)}</td><td>${r.expected_amount?brl(r.expected_amount):'—'}</td><td>${dateBR(r.expires_at)}</td><td><span class="badge ${s==='submitted'?'success':s}">${statusLabel(s)}</span></td><td><div class="table-actions">${S.profile.role==='admin'&&s==='pending'?'<button class="btn btn-secondary btn-sm" data-renew="'+r.id+'">Novo link</button><button class="btn btn-danger btn-sm" data-cancel="'+r.id+'">Cancelar</button>':''}${s==='submitted'?'<button class="btn btn-secondary btn-sm" data-req="'+r.id+'">Abrir recibo</button>':''}</div></td></tr>`}).join('')}</tbody></table></div>`;document.getElementById('newBtn')?.addEventListener('click',()=>{S.view='new';render()});document.querySelectorAll('[data-renew]').forEach(b=>b.onclick=()=>renew(b.dataset.renew));document.querySelectorAll('[data-cancel]').forEach(b=>b.onclick=()=>cancel(b.dataset.cancel));document.querySelectorAll('[data-req]').forEach(b=>b.onclick=()=>{const r=S.receipts.find(x=>x.request_id===b.dataset.req);if(r)openReceipt(r.id)})}
function newReq(){if(S.profile.role!=='admin'){S.view='dashboard';render();return}document.getElementById('content').innerHTML=`<div class="admin-head"><div><h2>Nova solicitação de recibo</h2><p>Crie um link exclusivo e temporário.</p></div></div><form id="nr" class="panel"><div class="grid"><div class="field full"><label class="required">Passeio / motivo do pagamento</label><input name="event_name" required placeholder="Ex.: Salto das Nuvens — 10/10/2026"></div><div class="field"><label class="required">Categoria</label><select name="category"><option>Transporte / Ônibus</option><option>Hotel / Pousada</option><option>Alimentação</option><option>Guia / Condutor</option><option>Atrativo / Ingresso</option><option>Fotografia</option><option>Seguro</option><option>Combustível</option><option>Locação</option><option>Outro</option></select></div><div class="field"><label>Valor previsto</label><input name="expected_amount" inputmode="decimal" placeholder="Ex.: 2.800,00"></div><div class="field"><label class="required">Data do serviço</label><input name="service_date" type="date" required></div><div class="field"><label class="required">Validade</label><select name="days"><option value="3">3 dias</option><option value="7" selected>7 dias</option><option value="15">15 dias</option><option value="30">30 dias</option></select></div><div class="field full"><label class="required">Descrição do serviço</label><textarea name="service_description" required></textarea></div></div><div class="actions"><button class="btn btn-primary">Gerar link do fornecedor</button></div></form>`;document.getElementById('nr').onsubmit=createReq}
async function createReq(e){e.preventDefault();const f=e.currentTarget,token=randomToken(32),hash=await sha256(token),days=Number(f.days.value),row={event_name:f.event_name.value.trim(),category:f.category.value,service_description:f.service_description.value.trim(),expected_amount:currencyInputToNumber(f.expected_amount.value)||null,service_date:f.service_date.value,expires_at:new Date(Date.now()+days*86400000).toISOString(),token_hash:hash,status:'pending',created_by:S.profile.id};const {error}=await supabaseClient.from('receipt_requests').insert(row);if(error){toast(error.message,'error');return}await load();share(token,row.event_name);S.view='requests';render()}
function share(token,name){const link=buildPublicLink(token);modal('<div class="modal-head"><div><h3>Link criado com sucesso</h3><span class="muted">'+escapeHtml(name)+'</span></div><button class="btn btn-secondary btn-sm" data-close>Fechar</button></div><div class="notice success">Este link funciona uma única vez. Depois que o fornecedor envia, ele fica bloqueado.</div><div class="field"><label>Link do fornecedor</label><textarea id="lnk" readonly>'+escapeHtml(link)+'</textarea></div><div class="actions"><button class="btn btn-secondary" id="copy">Copiar link</button><button class="btn btn-primary" id="wa">Enviar pelo WhatsApp</button></div>');document.getElementById('copy').onclick=async()=>{await navigator.clipboard.writeText(link);toast('Link copiado.')};document.getElementById('wa').onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent('Olá, tudo bem? 😊\n\nPreciso que você preencha e assine o recibo referente a *'+name+'*.\n\n'+link+'\n\nDepois do envio, o link será encerrado automaticamente.'),'_blank')}
async function renew(id){const token=randomToken(32),hash=await sha256(token),r=S.requests.find(x=>x.id===id);const {error}=await supabaseClient.from('receipt_requests').update({token_hash:hash,expires_at:new Date(Date.now()+7*86400000).toISOString(),status:'pending'}).eq('id',id);if(error){toast(error.message,'error');return}await load();share(token,r.event_name);render()}
async function cancel(id){if(!confirm('Cancelar este link?'))return;await supabaseClient.from('receipt_requests').update({status:'cancelled'}).eq('id',id);await load();render()}
function settings(){if(S.profile.role!=='admin'){S.view='dashboard';render();return}const s=S.settings||{};document.getElementById('content').innerHTML=`<div class="admin-head"><div><h2>Dados do contratante</h2><p>Usados no recibo e no PDF.</p></div></div><form id="set" class="panel"><div class="grid"><div class="field full"><label class="required">Nome / Razão social</label><input name="business_name" required value="${escapeHtml(s.business_name||'Trilheiros de Rondonópolis')}"></div><div class="field"><label>CNPJ</label><input name="cnpj" value="${escapeHtml(s.cnpj||'')}"></div><div class="field"><label>Telefone</label><input name="phone" value="${escapeHtml(s.phone||'')}"></div><div class="field full"><label>Endereço</label><input name="address" value="${escapeHtml(s.address||'')}"></div><div class="field"><label>Cidade</label><input name="city" value="${escapeHtml(s.city||'Rondonópolis')}"></div><div class="field"><label>UF</label><input name="state" maxlength="2" value="${escapeHtml(s.state||'MT')}"></div><div class="field full"><label>E-mail</label><input name="email" type="email" value="${escapeHtml(s.email||'')}"></div></div><div class="actions"><button class="btn btn-primary">Salvar dados</button></div></form>`;document.getElementById('set').onsubmit=saveSettings}
async function saveSettings(e){e.preventDefault();const f=e.currentTarget,p={business_name:f.business_name.value.trim(),cnpj:formatCpfCnpj(f.cnpj.value),phone:f.phone.value.trim(),address:f.address.value.trim(),city:f.city.value.trim(),state:f.state.value.toUpperCase(),email:f.email.value.trim(),updated_at:new Date().toISOString()};const {error}=await supabaseClient.from('app_settings').update(p).eq('id',1);if(error)toast(error.message,'error');else{await load();toast('Dados salvos.')}}
function openReceipt(id){const r=S.receipts.find(x=>x.id===id),q=reqFor(r);modal(`<div class="modal-head"><div><h3>Recibo ${escapeHtml(r.receipt_code)}</h3><span class="muted">Código ${escapeHtml(r.verification_code)}</span></div><button class="btn btn-secondary btn-sm" data-close>Fechar</button></div><div class="detail-grid"><div class="detail"><span>Fornecedor</span><strong>${escapeHtml(r.legal_name)}</strong></div><div class="detail"><span>CPF/CNPJ</span><strong>${formatCpfCnpj(r.cpf_cnpj)}</strong></div><div class="detail"><span>Referência</span><strong>${escapeHtml(q.event_name||'—')}</strong></div><div class="detail"><span>Categoria</span><strong>${escapeHtml(q.category||'—')}</strong></div><div class="detail"><span>Valor</span><strong>${brl(r.amount_received)}</strong></div><div class="detail"><span>Recebimento</span><strong>${dateBR(r.payment_date)}</strong></div></div><h4>Assinatura</h4><img class="signature-preview" src="${r.signature_data_url}"><div class="actions"><button class="btn btn-primary" id="pdfNow">Gerar PDF</button></div>`);document.getElementById('pdfNow').onclick=()=>generateReceiptPDF(r,q,S.settings)}
function modal(html){const el=document.createElement('div');el.className='modal-backdrop';el.innerHTML='<div class="modal">'+html+'</div>';document.body.appendChild(el);el.onclick=e=>{if(e.target===el||e.target.closest('[data-close]'))el.remove()}}
function exportCSV(){const rows=filtered(),head=['Recibo','Data','Fornecedor','CPF/CNPJ','Passeio','Categoria','Valor','Forma'],body=rows.map(r=>{const q=reqFor(r);return[r.receipt_code,dateBR(r.created_at),r.legal_name,formatCpfCnpj(r.cpf_cnpj),q.event_name,q.category,Number(r.amount_received).toFixed(2).replace('.',','),r.payment_method]});const csv='\ufeff'+[head,...body].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(';')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='recibos_trilheiros.csv';a.click()}
boot();
})();
