window.TRILHEIROS_RECEIPTS_CONFIG = {
  SUPABASE_URL: "",
  SUPABASE_ANON_KEY: "",
  BUSINESS_NAME: "Trilheiros de Rondonópolis",
  DEFAULT_LINK_DAYS: 7,
  WHATSAPP_NUMBER: "5566996926174",
  DEMO_MODE: true
};
